setup workflow

diff --git a/.github/workflows/prisma-migrations.yml b/.github/workflows/prisma-migrations.yml
--- a/.github/workflows/prisma-migrations.yml
+++ b/.github/workflows/prisma-migrations.yml
@@ -24,4 +24,5 @@ jobs:
       - name: Run seed
         env:
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
-        run: npx ts-node prisma/seed.ts
+        run: |
+          npx ts-node prisma/seed.ts || (echo "Seeding failed" && exit 1)
